### ISSUE TITLE
To what extend should we use GraphQL

### ISSUE THREAD

**Issue by BenjiTheC** [consiliumQ/docs#2]
> This issue is to discuss how should we construct the `GraphQL` schema, it's probably mostly about frontend as it's only a matter of what query to use for fetching data from the backend schema. I don't know GraphQL very well, most of the following part stands basically on practices that I _think_ (which mean not necessarily) are good. **Please share your points of view as we can all learn from each other.**

GraphQL is super cool, and I think that using GraphQL will dramatically improve the scalability and flexibility of our code base. Comparing to [`redux`](https://redux.js.org/), which is a abstraction of data and data related operation layer for traditional RESTful API calls, it allows us get rid of (at least most of) this extra middle layer and seamlessly connect the React components and data needed for rendering the components.

However, it's usually not a good idea to go from one extreme end to another. The way we structure GraphQL queries is crucial as we probably don't want to only make one query that fetches all data in a deeply nested tree-like structure, neither should we make too many "micro" queries for requesting tiny bits of data when we can probably fetch all at once. With the computation ability of modern computer, the major concern of performance should focus on making "just enough" networking calls to fetch sufficient data.

**Please share your opinions on how and where to fetch data using what GQL query**, either under this issue or in the channel. We can organize an in-person meeting to discuss about it next week.

**Comment by SecondThrow** [comment]
I need to review the GraphQL material before I can give an educated opinion on this. It would probably be good to meet up next week to discuss.

**Comment by KhanhNguyen03** [comment]
I am not particularly familiar with GraphQL but based on the class we had this week, I think it is powerful and gives us a sort of more tangible (idk how to say) set of data (the schemas) for us to fetch over the backend's data. I will do more reading on it and i'm fine with meeting next week as well
